{% set name = "autodock" %}
{% set version = "4.2.6" %}
{% set sha256 = "4b24ce4baf216a5e1a6a79bb664eeed684aed17cede64ff0061aa1bcc17874c4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: http://autodock.scripps.edu/downloads/autodock-registration/tars/dist{{ version|replace(".","") }}/autodocksuite-{{ version }}-src.tar.gz
  sha256: {{ sha256 }}
  patches:
    - AD4.1_bound.dat-AD4_parameters.dat.patch
    - autocomm.h.patch
    - constants.h.patch
    - osx.patch  # [osx]

build:
  number: 3
  skip: True  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - ulimit -a
    - ulimit -s unlimited && autodock4 --version
    - ulimit -s unlimited && autogrid4 --version
    - gen_tor_arg_list.sh  # [not win]

about:
  home: http://autodock.scripps.edu
  license: GPLv2
  license_family: GPL
  license_file: LICENSE
  summary: "AutoDock is a suite of automated docking tools. It is designed to predict how small molecules, such as substrates or drug candidates, bind to a receptor of known 3D structure."
