{% set name = "autodock" %}
{% set version = "4.2.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: http://autodock.scripps.edu/downloads/autodock-registration/tars/dist{{ version|replace(".","") }}/autodocksuite-{{ version }}-src.tar.gz
  sha256: 4b24ce4baf216a5e1a6a79bb664eeed684aed17cede64ff0061aa1bcc17874c4
  patches:
    - osx.patch # [osx]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - autodock4 --version
    - autogrid4 --version

about:
  home: http://autodock.scripps.edu
  license: GPLv2
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: "AutoDock is a suite of automated docking tools. It is designed to predict how small molecules, such as substrates or drug candidates, bind to a receptor of known 3D structure."
